services:
  symfony:
    build: .
    container_name: symfony-app
    environment: 
      - SYMFONY_ENV=dev
    # volumes: 
    #   - ./my-symfony-app:/var/www/symfony
    networks: 
      - symfony-net

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - ./helm-chart/files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./my-symfony-app/public:/var/www/symfony/public
    ports:
      - "8080:80"
    networks: 
      - symfony-net
    depends_on:
      - symfony

  db:
    deploy:
      replicas: 0
    image: postgres:15
    container_name: postgres_db
    environment: 
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: root
      POSTGRES_DB: symfony_db
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - symfony-net
    ports:
      - "5432:5432"

networks:
  symfony-net: 
    driver: bridge

volumes:
  postgres-data: 
    driver: local