image:
  repository: my-symfony-img
  tag: "1.0.0"
  pullPolicy: IfNotPresent

symfony:
  replica: 1
  name: symfony-app
  port: 9000
  targetPort: 9000
  resources: 
    memory: "512Mi"
    cpu: "500m"
  container:
    name: symfony
    image: my-symfony-img
    tag: "0.1.0"

nginx:
  replica: 1
  name: nginx
  port: 80
  targetPort: 80
  resources: 
    memory: "256Mi"
    cpu: "250m"
  container:
    name: nginx
    image: nginx
    tag: "1.27"
  
ingress:
  enabled: false
  host: my-sym-app.com
  tlsSecretName: nginx-tls

environment: prod

namespace: symfony