apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "common.namespace" . }}
  name: {{ .Values.symfony.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.symfony.replica }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.symfony.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.symfony.name }}
    spec:
      containers:
        - name: {{ .Values.symfony.container.name }}
          image: "{{ .Values.symfony.container.image }}:{{ .Values.symfony.container.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.symfony.targetPort }}
          resources:
            requests:
              memory: {{ .Values.symfony.resources.memory }}
              cpu: {{ .Values.symfony.resources.cpu }}
            limits:
              memory: {{ .Values.symfony.resources.memory }}
              cpu: {{ .Values.symfony.resources.cpu }}