apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "common.namespace" . }}
  name: {{ .Values.symfony.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.symfony.name }}
    environment: {{ .Values.environment | default "dev" }}
  ports:
    - protocol: TCP
      port: {{ .Values.symfony.port }}
      targetPort: {{ .Values.symfony.targetPort }}
  type: ClusterIP