apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "common.namespace" . }}
  name: {{ .Values.serviceName.nginx | default "nginx" }}
  labels:
    {{- include "common.labels" (dict "deploymentName" .Values.deploymentName.nginx "environment" .Values.environment) | nindent 4 }}
spec:
  selector:
    app: {{ .Values.deploymentName.nginx | default "nginx" }}
    environment: {{ .Values.environment | default "dev" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.nginx.port | default 80 }}
      targetPort: {{ .Values.service.nginx.targetPort | default 80 }}
  type: ClusterIP